### ISSUE TITLE
matplotlib widget returning "Error displaying widget"

### ISSUE THREAD

**Issue by arm61** [executablebooks/thebe#106]
Love the work

I am trying to get thebelab working through jupyter-book on the following webpage (http://pythoninchemistry.org/sim_and_scat/using_pylj/intro), the first cell shown makes use of the `%matplotlib widget` magic and is failing to render the output plots. I don't know if this is supported yet or not?

**Comment by moorepants** [comment]
This may be because require.js is not loaded. See here for a working example: https://thebe.readthedocs.io/en/latest/examples/ipympl_example.html

**Comment by moorepants** [comment]
Closing this issue, as it works in the current version of thebe. See the example above.
