### ISSUE TITLE
Usage of the same binder

### ISSUE THREAD

**Issue by sharypovandrey** [executablebooks/thebe#166]
Hi guys!
When I reload the page with Thebelab, it creates the new pod, like 
`https://my-kubernetes-domain.com/user/<github-username>-<repo>-<random-characters>/`. 
Is there a way to reuse this link? I'm trying to find the place where it gets generated.
I would be appreciated if you will point me in the code.
Thanks!

**Comment by akhmerov** [comment]
This is a great idea. Another use case for reusing the same binder instance is navigating between pages of the same website (e.g. build by [jupyter-book](https://github.com/jupyter/jupyter-book) or [jupyter-sphinx](https://github.com/jupyter/jupyter-sphinx)).

As a possible implementation I imagine setting a cookie that stores the binder URL.

**Comment by sharypovandrey** [comment]
@akhmerov yes, to store the URL in cookies is the first thing that comes to mind

**Comment by choldgraf** [comment]
I believe that @samlau95 implemented this in nbinteract, maybe he can give an idea for how it was done? I agree this would be quite useful for thebelab

**Comment by nthiery** [comment]
Generally speaking, we would want to have optimizations enabling to reach the same startup time as  [https://github.com/sagemath/sagecell](SageMath cell); this could include:
- reusing the same jupyter server for all pages that use the same environment behind the scene, regardless on whether they lie on the same web page. This presumably requires some additional feature on the binder side.
- kernel preheating: the jupyter server would maintain a pool of prestarted kernels ready to be served. This presumably can be implemented within the binder environment.

**Comment by choldgraf** [comment]
@nthiery I believe that this is already possible with Binder, as nbinteract persists the Binder session between pages by using cookies. @samlau95 can explain better than I, but I think it basically stores the Binder session URL along with the kernel information in a cookie and then re-uses that on subsequent pages.

**Comment by nthiery** [comment]
> @nthiery I believe that this is already possible with Binder, as nbinteract persists the Binder session between pages by using cookies. @samlau95 can explain better than I, but I think it basically stores the Binder session URL along with the kernel information in a cookie and then re-uses that on subsequent pages.

Cool! Thanks for the update.

This does not allow for sharing the same binder session between all
browsers or users that need the same environment though. The security
of it would need to be assessed, but this would enable fast
initialization even of the first page accessed, as long as someone
used that same environment recently.

**Comment by choldgraf** [comment]
ah - yes you are totally right, I'm assuming that the binder session only needs to be shared between the same user just from a different page. I think this by itself would be a big improvement.

(a note that I believe Juniper does the same thing - persisting Binder sessions across pages using local storage, so that's another place to look for inspiration)

**Comment by sharypovandrey** [comment]
@choldgraf yes, Juniper has special parameter `useStorage`. It uses the browser's localStorage to save the connection parameters, if the user navigates to a different page, the binder won't have to be requested from scratch.

**Comment by choldgraf** [comment]
@sharypovandrey any reason that you closed this? It still seems like a useful feature to have in Thebelab...

**Comment by sharypovandrey** [comment]
@choldgraf you are right, it would be great to develop this functionality

**Comment by SamLau95** [comment]
Having >1 user using the same Binder server is definitely possible but probably not something thebelab alone can do. Multiple users can use the same Binder server if they all know the unique server name that Binder generated. However, we don't have a way to communicate this server name to multiple users. Doing that will probably require a Binder endpoint, not an extra feature for thebelab.

**Comment by sharypovandrey** [comment]
@SamLau95 I see your point. I was thinking about use case when one user opens multiple web pages with Thebelab, these pages contain the code that will be executed on the Binder server. And we don't need to generate every time new Binder, we can reuse the same URL.
I.e. it is a scenario of the user who is learning programming language.

**Comment by choldgraf** [comment]
Yeah I agree that multi-user sharing would be much more complicated, but sharing a single binder session across multiple pages should be much easier (and also very useful)

**Comment by SamLau95** [comment]
Yup, having a single user reuse a Binder server across multiple pages is much easier. This works out of the box when using localstorage to remember Binder server info. This involves a few steps:

1. Store Binder info in localstorage when starting a server: https://github.com/SamLau95/nbinteract/blob/master/packages/nbinteract-core/src/NbInteract.js#L237-L239
2. Try to use localstorage first before trying to start a server: https://github.com/SamLau95/nbinteract/blob/master/packages/nbinteract-core/src/NbInteract.js#L202-L203
3. If localstorage fails, start a new server: https://github.com/SamLau95/nbinteract/blob/master/packages/nbinteract-core/src/NbInteract.js#L178-L184

**Comment by sharypovandrey** [comment]
Guys, sorry for the silly question, I add this feature to the source code, then I want to debug it, do I have to use the webpack to generate the file like `https://unpkg.com/thebelab@^0.4.0`? And what is the correct way for it? I have checked the

**Comment by sharypovandrey** [comment]
I use `npx webpack -o thebelab.js`, works well

**Comment by akhmerov** [comment]
Should this be closed? I verified that refreshing the page uses the same kernel. @sharypovandrey can you confirm that https://thebe.readthedocs.io/en/latest/ works the way you'd like?

**Comment by sharypovandrey** [comment]
@akhmerov I have tested this feature and everything works fine

**Comment by choldgraf** [comment]
yahoo! 🎉
