### ISSUE TITLE
Move codeMirrorOptions outside binderOptions?

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/thebe#223]
I noticed that right now thebelab is looking inside `binderOptions` for the codeMirror config:

https://github.com/minrk/thebelab/blob/8b6d82c24727ae67685c89bea99f38031df12ea1/src/thebelab.js#L263

Why is that? Isn't CM something that would be used regardless of the backend supplying the kernel?

**Comment by stevejpurves** [comment]
done! see now functional see https://executablebooks.github.io/thebe/
Some draft docs in `apps/docs-core`
