### ISSUE TITLE
Persist a server connection across pages

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/thebe#224]
Many times, a user switches pages within the same domain and wants to run some more code. Right now, Thebelab will request a **new** binder session each time this happens, which puts burden on mybinder.org.

It would be great if we stored the Binder session information to re-use the session if it exists. Then a user would get super fast sessions in subsequent pageloads.

@ines kindly showed us where she does this in Juniper, I think we should follow the same pattern!

https://github.com/ines/juniper/blob/master/src/index.js#L57-L64

**Comment by akhmerov** [comment]
Juniper seems to [use an explicit timeout](https://github.com/ines/juniper/blob/master/src/index.js#L121-L124) of one hour since the last kernel was requested in order to determine whether a new binder needs to be requested. I am wondering whether #255 is a more reliable approach.

**Comment by akhmerov** [comment]
A *kernel* usually makes sense to make page-specific, otherwise one may face side-effects from wrong things being defined, etc. I've updated the issue title to make clear that we want to persist the server connection.

**Comment by choldgraf** [comment]
yep - good point, agreed we want "one kernel per page", but "one binder session per browser viewing session"
