### ISSUE TITLE
Codemirror does not take effect

### ISSUE THREAD

**Issue by linjie98** [executablebooks/thebe#241]
Hi @minrk I tried to add a theme to the editor through the following configuration, but it didn't work.
I read the previous issues, but it still doesn’t work
`<script type="text/x-thebe-config">
    {
      bootstrap: true,
      kernelOptions: {
        name: "python3",
        serverSettings: {
          "baseUrl": "http://127.0.0.1:8888",
          "token": "test-secret"
        }
      },
      codeMirrorConfig: {
          theme: "abcdef"
      },
    }
  </script>`
Can you tell me what should I do, thanks

**Comment by ymdahi** [comment]
Just ran into this issue. Would be nice to be able to add some style/have control over the code editor, like https://codemirror.net/demo/theme.html#eclipse

**Comment by stevejpurves** [comment]
this is now functional see https://executablebooks.github.io/thebe/ for `darcula` in place
