### ISSUE TITLE
Upgrade JupyterLab dependencies

### ISSUE THREAD

**Issue by minrk** [executablebooks/thebe#251]
our JupyterLab dependencies are pretty out-of-date at this point. Updating them generally needs to be done all at once with updates to our use of the the APIs that have changed. This is probably easiest for someone already familiar with JupyterLab APIs, as the failures can be 

Current status, from `npm outdated`:

```
Package                            Current  Wanted          Latest  Location
@jupyter-widgets/base                2.0.2   2.0.2   4.0.0-alpha.2  thebe
@jupyter-widgets/controls            1.5.3   1.5.3   3.0.0-alpha.2  thebe
@jupyter-widgets/html-manager       0.18.4  0.18.4  0.20.0-alpha.2  thebe
@jupyter-widgets/output              2.0.1   2.0.1   4.0.0-alpha.2  thebe
@jupyterlab/codemirror               1.2.8   1.2.9           2.2.3  thebe
@jupyterlab/mathjax2                 1.2.0   1.2.0           2.2.0  thebe
@jupyterlab/outputarea               1.2.9  1.2.10           2.2.3  thebe
@jupyterlab/services                 4.2.2   4.2.3           5.2.4  thebe
@jupyterlab/theme-light-extension    1.2.8   1.2.9           2.2.5  thebe
```

Two things we might want to wait for before doing this:

1. some more tests to have an easier CI check to be more confident about whether upgrades break things
2. impending jupyterlab 3.0 release (the reason for the alphas above) since that includes some big changes that should land pretty soon

**Comment by stevejpurves** [comment]
it looks like this has already been moved forward.

![image](https://user-images.githubusercontent.com/1473646/126233039-1c0d23d2-a339-485f-9942-22964869c310.png)

So this one is good to close?

**Comment by choldgraf** [comment]
ah yes I believe from https://github.com/executablebooks/thebe/commit/c1b35fa6fdc27b6750586cd3653418ed97d0f9f5
