### ISSUE TITLE
Create an examples section in the Sphinx docs showing thebe working with popular libraries with custom outputs

### ISSUE THREAD

**Issue by moorepants** [executablebooks/thebe#253]
Many libraries implement custom outputs for rich display in Jupyter Notebook and Jupyter Lab, but they don't always display as expected with thebe. Some of these require some user tweaks to get working with thebe and sometimes there is a thebe issue that may prevent them from working. We can start by moving the things in the `examples/` directory to the Sphinx docs in `docs` and then open PRs for new Sphinx pages showing off other libraries. Here are a list of some libraries:

- [x] move `examples/` to `docs/examples/` and format for sphinx
- [ ] bokeh
- [x] bpplot
- [x] ipycytoscape
- [x] ipyleaflet: #265 
- [x] ipympl
- [x] plotly: #269 
- [x] pythreejs: #262

You'll probably have to find a repo setup for repo2docker for each library that has the libraries properly installed (usually on that library's page) and use that for the page in the sphinx docs.

**Comment by moorepants** [comment]
@sandertyu created this repo showing some libraries that do and don't work that may be helpful. Some of that info could be transferred here to this issue if needed: https://github.com/sandertyu/widgetstuffs

**Comment by moorepants** [comment]
One other useful note is that many of these libraries can display custom Jupyter output that is essentially static wrt to the attached kernel (after the cell has been run) but that many examples also show off the interactive Jupyter widget functionality that is not static wrt to the attached kernel. The later may have more issues working than the former, so getting the former to work is the best starting point.

**Comment by moorepants** [comment]
I'm working on a pythreejs page.

**Comment by celine168** [comment]
Noah and I are working on ipympl and ipyleaflet I believe.

**Comment by moorepants** [comment]
gonna try plotly now

**Comment by celine168** [comment]
I'm working on ipycytoscape as well, forgot to mention that.

**Comment by celine168** [comment]
As an update to these can be checked off: 
* [ipympl](https://thebelab.readthedocs.io/en/latest/examples/ipympl_example.html)
* [ipytoscape](https://thebelab.readthedocs.io/en/latest/examples/ipycytoscape_example.html)
* [bqplot](https://thebelab.readthedocs.io/en/latest/examples/bqplot_example.html)

**Comment by moorepants** [comment]
Done!

**Comment by moorepants** [comment]
There is an issue open for bokey support #112, so I'm closing this.
