### ISSUE TITLE
Improve styling of thebe elements

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/thebe#256]
After migration to the sphinx-book-theme, thebe elements look like this upon activation:

![image](https://user-images.githubusercontent.com/2069677/96334936-be4e8600-1074-11eb-9e49-017315da4f11.png)

I think this would look better without line separators in the source code, and the button styling could be improved.

**Comment by akhmerov** [comment]
Also the code really doesn't look like CodeMirror abcdef theme...

**Comment by moorepants** [comment]
#184 is relevant. Maybe it needs to ship with minimal styling.
