### ISSUE TITLE
Cell magic as <pre> attribute?

### ISSUE THREAD

**Issue by psychemedia** [executablebooks/thebe#26]
Thinking of ways to simplify the page user experience, I wonder if it would be useful to specify an IPython cell magic attribute (`%%whatever`) that can be automatically prepended to the contents of a code cell so that the user can run the cell directly in a cell magic mode?

For the UI, the cell style could be changed or perhaps the `run` button text changed to `run as %%whatever` magic? Or maybe two buttons - one to run the cell as a normal code cell, the other to run it with the magic?

**Comment by minrk** [comment]
Hm. That's baking a bit more kernel-specific logic into this than I'd like, since Jupyter cells are entirely interpreted into the kernel. What magics are you thinking of using?

**Comment by psychemedia** [comment]
some latex ones eg `tikz`, to allow people to draw diagrams

**Comment by akhmerov** [comment]
@psychemedia is the issue still relevant? Overall the proposal seems to not align with the overall design principle "executing code like in Jupyter".

I think a simpler and architecturally better approach to achieve your desired outcome is by using IPython's input transformers, like [here](https://github.com/LukeRoantree4815162342/pioton/blob/master/pioton/pioton.py#L344) and setting up the transformers in the background when the kernel starts, see [here](https://thebe.readthedocs.io/en/latest/howto/initialize_cells.html#running-cells-when-thebe-is-initialized).

Based on the above considerations, I'm closing the issue, but let me know if you disagree.

**Comment by psychemedia** [comment]
@akhmerov It's been time since I last exploring this. I think my rationale was if someone wanted to co-opt a thebelab page and configure to run the code cells as block magicked cells and not have to explicitly assert the `%%` magic themselves. (IIRC, I think I was exploring the idea of richer of range of user-selectable cell types in notebooks, where the new user types were essentially just block magicked cells.

Happy for this to be closed; apols for not arguing a position / use case more clearly when I originally posted it (not least because I didn't clearly and explicitly capture and describe my intended use case in the original issue post.)
