### ISSUE TITLE
Remove the many stale branches

### ISSUE THREAD

**Issue by Miniland1333** [executablebooks/thebe#296]
**Is your feature request related to a problem? Please describe.**

This issue is related to the removal of greenkeeper and renovate in favor of dependabot.

**Describe the solution you'd like**

Removing all of the outdated greenkeeper and renovate branches. The bots are no longer active and there are three pages of stale branches. There also are a few other stale branches that likely should be removed as well since no one has used them for over a year.

**Describe alternatives you've considered**

We can leave it alone, though it makes it excessively cluttered to swap/merge branches. Since these branches are very old and stale, I don't see any advantage to leaving them alone.

**Additional context**

https://github.com/executablebooks/thebe/branches/stale

**Comment by choldgraf** [comment]
+1 from me

**Comment by minrk** [comment]
Removed! I thought these bots were supposed to cleanup after themselves. Hopefully dependabot does better.

**Comment by Miniland1333** [comment]
> Removed! I thought these bots were supposed to cleanup after themselves. Hopefully dependabot does better.

The bots usually clean up after themselves, but since the dependencies they were monitoring weren't resolved until this last sprint they didn't have the opportunity to clean up (since they had been removed).
