### ISSUE TITLE
Releasing a newer versions or master branch of Thebe to unpkg

### ISSUE THREAD

**Issue by celine168** [executablebooks/thebe#322]
**Is your feature request related to a problem? Please describe.**

My team is interested in using the latest version of Thebe on master (or a more recent commit), rather than the current release in unpkg, which is over a year old. 

I understand that #285 may be a related issue as the docs currently cannot build the latest version of Thebe.

**Describe the solution you'd like**

Would it be possible to deploy master branch versions of Thebe to unpkg or release new versions?

**Comment by moorepants** [comment]
Another option is to release thebe more frequently. @minrk is that possible? Can we help with that?

**Comment by choldgraf** [comment]
I am all for releasing Thebe more frequently. It should be as simple as: https://thebe.readthedocs.io/en/latest/contribute.html#releasing-thebe

somebody wanna try giving this a shot?

**Comment by moorepants** [comment]
We just discussed this in our meeting. One idea was to automate releasing on each merged PR. Thoughts on that? Since this isn't a library, we thought it seemed reasonable to automate the releases. This could also solve #285.

Are there any criteria for releasing besides review the changes and decide what semantic version value to bump? Would the semantic version only rules for major only apply if we change configuration options as that is the only input by a user of the thebe application?

**Comment by choldgraf** [comment]
I basic approach that I think `executablebooks/` is going to follow is to create a GitHub label for `block-release` - this will be used for issues that should block any new releases until they're resolved (e.g., a bad bug in master, etc). Beyond those tags, people are encouraged to release whenever they want, and often, for anything that is not a "major" release

**Comment by narrator0** [comment]
I agree that we can deploy every time when something is merged into master expect for major releases. I suggest changing the github actions to deploy on every push on master. We can also use something like [husky](https://github.com/typicode/husky) to enforce a version uptick the version number in `package.jason` every time a person pushes so that it is easy to tag each release.

**Comment by celine168** [comment]
I can go through the commits made since the last release and create a changelog, as per EBP guidelines.
But, if we want to deploy each time we push to master, does this mean that the changelog should update every time someone pushes a commit?

**Comment by moorepants** [comment]
I pushed 0.6.0 to github but I'm not seeing anything here: https://unpkg.com/browse/thebelab@0.6.0/. I'm not seeing any Github actions that indicate something ran to push to upkg.com either.

**Comment by moorepants** [comment]
Looks like you need to make a Github release to trigger the action, did that: https://github.com/executablebooks/thebe/releases/tag/v0.6.0

**Comment by moorepants** [comment]
It is now up, but note it is under `thebe` not `thebelab`: https://unpkg.com/browse/thebe@0.6.0/

**Comment by choldgraf** [comment]
@celine168 let's not worry about the details of a changelog per deploy - we should update the changelog on a semi-regular basis (perhaps each quarter) with major changes and especially deprecations so that others can follow along.

**Comment by celine168** [comment]
@choldgraf  That sounds good to me! Thanks for clarifying :) 

@moorepants Thank you for releasing! 🎉

**Comment by choldgraf** [comment]
I think we can close this issue once we are happy with the release documentation for this repository, @moorepants was working on that a bit, are there other changes we need to make?

**Comment by narrator0** [comment]
I suggest we can do an automatic release on every PR merged into master. This can be done by:

1. Use [hustky](https://github.com/typicode/husky) to force increase the version number in `package.json` when push
2. Change Github Action to tag and release on every PR merge

@choldgraf what do you think about this idea? I can try to create a PR of this if you think this is a good idea.

**Comment by choldgraf** [comment]
I'm not super familiar with best-practices in javascript releases, so I'll defer to others if they have strong opinions. It sounds fine to me though...I wonder if @minrk has thoughts?

**Comment by moorepants** [comment]
We are releasing more often now (as needed). It is still a manual process, but seems to solve this sufficiently. Closing.
