### ISSUE TITLE
Changing default binder repository, it still uses "binder-examples/requirements",

### ISSUE THREAD

**Issue by hackenjoe** [executablebooks/thebe#364]
Hi I have a binding repository that I would like to embed in thebelab script and run python scripts from there. I put the whole thing in a juptyter book, strictly by template, but every time it loads the default repository `binder-examples/requirements` and not `hackenjoe/requirements`. Because in my repository I have additional libraries (such as PyTorch) installed which I want to use. But each time if I import torch it says module not  found. On binder live environment it is working. Both are Github Binder projects. How can I fix this?

```<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js"></script>
<script type="text/x-thebe-config">
  {
    requestKernel: true,
    binderOptions: {
	  repo: "hackenjoe/requirements",
	  ref: "master",
    },
	kernelOptions: {
	  kernelName: "python3",
	}
  }
</script>
<script src="https://unpkg.com/thebe@latest/lib/index.js"></script>
```

**Comment by moorepants** [comment]
That's odd. We have examples that use different repos that are function correctly in the docs. For example: file:///home/moorepants/src/thebe/docs/_build/html/examples/plotly-example.html

You could try prior versions of thebe from unpkg to see of something is different in the latest version. Also, have a look at your browser's console output to see if there are any clues there. You can paste that info here.

**Comment by hackenjoe** [comment]
I solved the problem but I actually dont know how. I think that it just took some time to load the individual binder session for the first time. I have read that the more often the same binder instance is used the faster the instance is loaded. Another cause might be a faulty cache.

**Comment by moorepants** [comment]
A fresh repo can take some time to build. I recommend building using the web interface at mybinder.org to watch the full output as it builds the first time. Going to close this issue. Thanks.
