### ISSUE TITLE
ipywidgets "default.js:127 TypeError: Cannot read property 'emit' of undefined"

### ISSUE THREAD

**Issue by So-Cool** [executablebooks/thebe#374]
**Describe the bug**

An `ipywidgets`' button does not work through Thebe when embedded on a Jupyter Book page.
Pressing a button after launching Thebe gives the following error in the web browser's console:
```
default.js:127 TypeError: Cannot read property 'emit' of undefined
    at Object.output (manager.js:54)
    at e.onIOPub (services-shim.js:97)
    at t.KernelShellFutureHandler._handleIOPub (future.js:204)
    at async t.KernelShellFutureHandler.handleMsg (future.js:173)
    at async v._handleMessage (default.js:1038)
(anonymous) @ default.js:127
Promise.catch (async)
_onWSMessage @ default.js:124
```

**To Reproduce**

1. Embed an `ipywidgets`' button on a Jupyter Book page
2. Launch Thebe (via *Live Code*)
3. Click the button

For example, see [this page](https://problog-template.simply-logical.space/src/text/bayesian_networks-mnb.html) with button widgets.

**Expected behavior**

Clicking the button should execute the connected Python function.

**Environment**

- Python Version [e.g. 3.7.1]: 3.7.10
- Package versions or output of `jupyter-book --version`:
  * jupyter-book 0.10.1
  * sphinx-thebe 0.0.8
- Operating System: Ubuntu 18.04.5 LTS

**Additional context**

N/A

**Comment by moorepants** [comment]
Thanks. Ipywidgets has very limited functionality with thebe. Related issues are #111 and #226.

**Comment by moorepants** [comment]
We've just merged some fixes that improve ipywidget functionality. Can you test with the tip of the master branch to see if your issue is resolved?

**Comment by So-Cool** [comment]
Apologies for not acting upon this earlier, @moorepants. Everything appears to work now. Thanks so much!
