### ISSUE TITLE
Duplicate labels

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/thebe#396]
There seem to be two different `enhancement` labels:

![image](https://user-images.githubusercontent.com/2069677/116793614-00e32780-aac8-11eb-9d3c-9a71a1d63fda.png)

Upon clicking on the light blue, I get the listing of the other one. Furthermore it seems impossible to assign the light blue one. Is it perhaps inherited from the ebp org? Should one of these be deleted?

**Comment by choldgraf** [comment]
I think it just is a github cacheing bug when old labels are deleted, I've seen it happen in other repositories too

**Comment by akhmerov** [comment]
Thanks, I replaced all the remaining "unreachable" ones.
