### ISSUE TITLE
Run cell busy/progress indicator

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/thebe#422]
**the problem**

At the moment, after a kernel is available and connected, when we press [run] on a cell there is no visual feedback at all. The action buttons themselves stay enabled, and there is no other indication of busy'ness available. 

In some cases, execution is so fast that this is not noticeable but for other use cases for example the Leaflet and Cytoscape examples, is tasks a few seconds for the execution to complete.

**the desired solution**
This leads to impatience and multiple clicks. It's also not clear what the impact of multiple clicks are or if they are indeed registered. This leaves the user confused.

A simple improvement would be to add some form of busy indicator, to at least show the click has been registered.

**Describe alternatives you've considered**

We can also consider disabling the buttons once execution has been requested but it's not clear if edge cases are currently relying on that.  We would disable only the run button and have this re-enabled when on success, or failure, or kernel restart. I think this should be done in addition to a busy indicator if at all.

**Comment by psychemedia** [comment]
In terms of UI, in classic notebook I use a cell status indicator extension that highlights cell execution in the margin:

![image](https://user-images.githubusercontent.com/82988/126900337-c72a9ae0-c73f-4608-b01a-ad024ee1eaaf.png)

Something a bit subtler showing a coloured vertical bar in the gutter might be enough of an indication.

**Comment by choldgraf** [comment]
I believe @stevejpurves actually already tackled this one! @stevejpurves is this good to close?

**Comment by stevejpurves** [comment]
ah yes, this is good to close as the PR was merged. It's a spinner style indicator rather than the linear progress, @psychemedia once that's out would be interested in your take on it.
