### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/thebe#423]
This repo still has a master branch in place, we should rename this asap.

I'm not clear on any downstream implications and can't see any script or action dependencies that won't be fixed once the default branch is changed.

So this will be a simple settings change and then users updating their remotes accordingly?

**Comment by rowanc1** [comment]
See https://github.com/executablebooks/meta/issues/427 as well for the checklist.

**Comment by stevejpurves** [comment]
done!
