### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/thebe#43]
Firstly, I really love the implementation and the simplicity of using thebelab, it looks like a great tool!

I also realize that the project is in initial stages, and therefore my questions below are premature and will be answered by the documentation.

* Is there a JS API for modifying thebelab configuration? The use cases for this would be:
  - Allowing a user to switch between an online service and a local notebook for better response times/availability.
  - Allowing users to provide their own access token when running a local notebook for better security
* Is there an API for sending code to the kernel? The use case for this would be automatically executing initialization code.
* What are the requirements on the server? I understand that it should have jupyterlab (or shouldn't it?), but is there anything more specific?
* If I want fancy rendering of the outputs provided by a jupyterlab extension, where should this extension go?

**Comment by minrk** [comment]
> Is there a JS API for modifying thebelab configuration?

Configuration can be declarative, as in the examples, and is mostly a wrapper of the JupyterLab configuration for connecting to kernels. For instance:

```html
  <script type="text/x-thebe-config">
    {
      bootstrap: true,
      kernelOptions: {
        name: "python3",
        serverSettings: {
          "baseUrl": "http://127.0.0.1:8888",
          "token": "test-secret"
        }
      },
    }
  </script>
```

You can do the same with javascript:

```javascript
cfg = {
      kernelOptions: {
        name: "python3",
      }
if (useLocal) {
    cfg.kernelOptions.serverSettings = {
          "baseUrl": "http://127.0.0.1:8888",
          "token": "test-secret"
        }
} else {
    cfg.kernelOptions.serverSettings = {
          "baseUrl": "https://my-server.com/user/username",
          "token": "other-secret"
        }
}
thebelab.bootstrap(cfg);
```

> Is there an API for sending code to the kernel?

The Kernel is a JupyterLab [Kernel](http://jupyterlab.github.io/jupyterlab/interfaces/_services_src_kernel_kernel_.kernel.ikernel.html#requestexecute) object. We put it on the page, then you can interact with it [via the jupyterlab api](http://jupyterlab.github.io/jupyterlab/interfaces/_services_src_kernel_kernel_.kernel.ikernel.html#requestexecute).

So if you want to send some code on initialization prior to hooking up the kernel:

```javascript
let cells = thebelab.renderAllCells();
thebelab
  .requestKernel(kernelOptions)
  .then(function(kernel) {
    kernel
      .requestExecute({code: "my_initialize"})
      .then(function () {
        thebelab.hookupKernel(kernel, cells)
      });
  });
```

> What are the requirements on the server?

It must be a Jupyter notebook server >= 4.x. I'm not sure exactly how recent, maybe 4.1. JupyterLab is purely a client for Jupyter, it does not have a server component, so any Jupyter server will do.

> If I want fancy rendering of the outputs provided by a jupyterlab extension, where should this extension go?

This is an *excellent* question, and I don't yet have an answer. Ideally, it won't require any additional builds and can be achieved via additional script tags to put the renderer on the page, and thebelab will just pick it up. We'll need to register it with RenderMime, I just don't know what the current mechanism for doing that is. If you'd like to explore how that might work, I would love that.

**Comment by lavvy** [comment]
please what is wrong with this script . I cant get the value of a by typing a in the cell. 
I get error a is not defined

  <script type="text/javascript" src="thebelab.js"></script>
  <script>
    cfg = {
      bootstrap: true,
      binderOptions: {
        repo: "binder-examples/requirements",
      },
      kernelOptions: {
        name: "python3",
      },
    }
 thebelab.bootstrap(cfg);

var cells = thebelab.renderAllCells();
thebelab.requestKernel(kernelOptions)
  .then(function(kernel) {
    kernel.requestExecute({ code: 'a = 1' })
      .then(function () {
        thebelab.hookupKernel(kernel, cells)
      });
  });

  </script>
