### ISSUE TITLE
Description, website, topics

### ISSUE THREAD

**Issue by slel** [executablebooks/thebe#52]
Currently (2018-06-05), this GitHub repo at [0] reads

> *No description, website, or topics provided.*

Suggestion: add a description, such as:

> ThebeLab: turning static HTML pages into live documents

and a website, such as [1].

Additionally, the main README.md could point to the blog post [2].

- [0] https://github.com/minrk/thebelab
- [1] https://minrk.github.io/thebelab/
- [2] https://blog.ouseful.info/2017/12/18/run-python-code-embedded-in-html-via-a-jupyter-kernel/

**Comment by nthiery** [comment]
Done for the link to the blog post.

**Comment by akhmerov** [comment]
Just going over the open issues.

- [x] The repository description links to the documentation page
- [x] The readme links to the blog post

Therefore it seems this may be closed. Let me know or reopen directly if something still needs to be done.
