### ISSUE TITLE
Empty import from thebe-lite

### ISSUE THREAD

**Issue by shaielc** [executablebooks/thebe#637]
### Describe the bug

**context**
Copied the example from `thebe-lite` for TS:
```
import { makeConfiguration, ThebeServer } from 'thebe-core';
import { setupThebeLite } from 'thebe-lite';

setupThebeLite();

const config = makeConfiguration({});
const server = new ThebeServer(config);
```
for use in react (brand new project)

**bug**
I get an exception `setupThebeLite` is not a function. looking at the value it was undefined.

<details><summary>turbo-build.log</summary>
<p>

> thebe-lite@0.2.3 build
> npm-run-all -l clean -p build:bundle declarations

[clean] 
[clean] > thebe-lite@0.2.3 clean
[clean] > rm -rf ./dist
[clean] 
[declarations] 
[declarations] > thebe-lite@0.2.3 declarations
[declarations] > tsc  --project ./tsconfig.json --declaration --emitDeclarationOnly --outDir dist/types
[declarations] 
[build:bundle] 
[build:bundle] > thebe-lite@0.2.3 build:bundle
[build:bundle] > webpack --config webpack.config.cjs
[build:bundle] 
[build:bundle] <i> [HookShellScriptPlugin] Running script: node bin/stubContentsApi.js
[build:bundle] assets by path *.js 1.13 MiB
[build:bundle]   assets by chunk 258 KiB (id hint: vendors)
[build:bundle]     asset 609.thebe-lite.min.js 160 KiB [emitted] [minimized] (id hint: vendors) 2 related assets
[build:bundle]     asset 686.thebe-lite.min.js 98.6 KiB [emitted] [minimized] (id hint: vendors) 2 related assets
[build:bundle]   asset thebe-lite.min.js 888 KiB [emitted] [minimized] [big] (name: app) 2 related assets
[build:bundle]   asset 328.thebe-lite.min.js 5.91 KiB [emitted] [minimized] 2 related assets
[build:bundle]   asset service-worker-dddfe83.js 1.42 KiB [emitted] [immutable] [from: ../../node_modules/@jupyterlite/server/lib/service-worker.js] [minimized] (auxiliary name: app)
[build:bundle]   asset 562.thebe-lite.min.js 480 bytes [emitted] [minimized] 1 related asset
[build:bundle] assets by path pypi/ 29.7 KiB
[build:bundle]   asset pypi/pyodide_kernel-0.0.8-py3-none-any.whl 8.03 KiB [emitted] [from: ../../node_modules/@jupyterlite/pyodide-kernel/pypi/pyodide_kernel-0.0.8-py3-none-any.whl] (auxiliary id hint: vendors)
[build:bundle]   asset pypi/piplite-0.0.8-py3-none-any.whl 6.56 KiB [emitted] [from: ../../node_modules/@jupyterlite/pyodide-kernel/pypi/piplite-0.0.8-py3-none-any.whl] (auxiliary id hint: vendors)
[build:bundle]   asset pypi/ipykernel-6.9.2-py3-none-any.whl 6.36 KiB [emitted] [from: ../../node_modules/@jupyterlite/pyodide-kernel/pypi/ipykernel-6.9.2-py3-none-any.whl] (auxiliary id hint: vendors)
[build:bundle]   asset pypi/all.json 4.17 KiB [emitted] [from: ../../node_modules/@jupyterlite/pyodide-kernel/pypi/all.json] (auxiliary id hint: vendors)
[build:bundle]   asset pypi/widgetsnbextension-3.6.4-py3-none-any.whl 2.28 KiB [emitted] [from: ../../node_modules/@jupyterlite/pyodide-kernel/pypi/widgetsnbextension-3.6.4-py3-none-any.whl] (auxiliary id hint: vendors)
[build:bundle]   asset pypi/widgetsnbextension-4.0.7-py3-none-any.whl 2.28 KiB [emitted] [from: ../../node_modules/@jupyterlite/pyodide-kernel/pypi/widgetsnbextension-4.0.7-py3-none-any.whl] (auxiliary id hint: vendors)
[build:bundle] orphan modules 1010 KiB [orphan] 50 modules
[build:bundle] runtime modules 12.3 KiB 23 modules
[build:bundle] javascript modules 3.03 MiB
[build:bundle]   modules by path ../../node_modules/ 3.02 MiB 331 modules
[build:bundle]   modules by path ./src/ 4.9 KiB 4 modules
[build:bundle]   node-fetch (ignored) 15 bytes [built] [code generated]
[build:bundle]   node-fetch (ignored) 15 bytes [built] [code generated]
[build:bundle] asset modules 252 bytes (javascript) 29.7 KiB (asset)
[build:bundle]   ../../node_modules/@jupyterlite/pyodide-kernel/pypi/all.json 42 bytes (javascript) 4.17 KiB (asset) [built] [code generated]
[build:bundle]   ../../node_modules/@jupyterlite/pyodide-kernel/pypi/ipykernel-6.9.2-py3-none-any.whl 42 bytes (javascript) 6.36 KiB (asset) [built] [code generated]
[build:bundle]   ../../node_modules/@jupyterlite/pyodide-kernel/pypi/piplite-0.0.8-py3-none-any.whl 42 bytes (javascript) 6.56 KiB (asset) [built] [code generated]
[build:bundle]   ../../node_modules/@jupyterlite/pyodide-kernel/pypi/pyodide_kernel-0.0.8-py3-none-any.whl 42 bytes (javascript) 8.03 KiB (asset) [built] [code generated]
[build:bundle]   ../../node_modules/@jupyterlite/pyodide-kernel/pypi/widgetsnbextension-3.6.4-py3-none-any.whl 42 bytes (javascript) 2.28 KiB (asset) [built] [code generated]
[build:bundle]   ../../node_modules/@jupyterlite/pyodide-kernel/pypi/widgetsnbextension-4.0.7-py3-none-any.whl 42 bytes (javascript) 2.28 KiB (asset) [built] [code generated]
[build:bundle] 
[build:bundle] WARNING in ../../node_modules/@jupyterlite/pyodide-kernel/lib/worker.js 1:226-233
[build:bundle] Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
[build:bundle]  @ ../../node_modules/@jupyterlite/pyodide-kernel/lib/index.js 7:0-25 7:0-25
[build:bundle]  @ ../../node_modules/@jupyterlite/pyodide-kernel-extension/lib/index.js
[build:bundle]  @ ./src/jlite.ts
[build:bundle]  @ ./src/index.ts 5:16-34
[build:bundle] 
[build:bundle] WARNING in ../../node_modules/@jupyterlite/pyodide-kernel/lib/worker.js 1:382-389
[build:bundle] Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
[build:bundle]  @ ../../node_modules/@jupyterlite/pyodide-kernel/lib/index.js 7:0-25 7:0-25
[build:bundle]  @ ../../node_modules/@jupyterlite/pyodide-kernel-extension/lib/index.js
[build:bundle]  @ ./src/jlite.ts
[build:bundle]  @ ./src/index.ts 5:16-34
[build:bundle] 
[build:bundle] WARNING in ../../node_modules/@jupyterlite/pyodide-kernel/lib/worker.js 7:8494-8503
[build:bundle] Critical dependency: the request of a dependency is an expression
[build:bundle]  @ ../../node_modules/@jupyterlite/pyodide-kernel/lib/index.js 7:0-25 7:0-25
[build:bundle]  @ ../../node_modules/@jupyterlite/pyodide-kernel-extension/lib/index.js
[build:bundle]  @ ./src/jlite.ts
[build:bundle]  @ ./src/index.ts 5:16-34
[build:bundle] 
[build:bundle] WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
[build:bundle] This can impact web performance.
[build:bundle] Assets: 
[build:bundle]   thebe-lite.min.js (888 KiB)
[build:bundle] 
[build:bundle] WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
[build:bundle] Entrypoints:
[build:bundle]   app (888 KiB)
[build:bundle]       thebe-lite.min.js
[build:bundle] 
[build:bundle] 3 warnings have detailed information that is not shown.
[build:bundle] Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.
[build:bundle] 
[build:bundle] webpack 5.76.0 compiled with 5 warnings in 6982 ms
[build:bundle] <i> [HookShellScriptPlugin] Completed script: node bin/stubContentsApi.js

</p>
</details> 

### Reproduce the bug

1. create a new react project
2. `npm i thebe-lite`
3. take the code from the example
4. run the react app

### List your environment

node: v18.16.0

**Comment by stevejpurves** [comment]
hi @shaielc 

I think what you could be missing here is the step of copying the `thebe-lite` assets into the `dist` folder.

Note that `thebe-lite` always has to be loaded to the page as a js bundle, installing via npm will not bring it in to your build process.

See the `copy:lite` script in [the package.json](https://github.com/executablebooks/thebe/blob/3d0d729a9257686d9c364fcb6b13ac01ad0c0a85/apps/demo-core/package.json#L10) of the demo app.

and also note how the index.html is set up [here](https://github.com/executablebooks/thebe/blob/3d0d729a9257686d9c364fcb6b13ac01ad0c0a85/apps/demo-core/static/index.html#L22)

**Comment by shaielc** [comment]
Thanks for the, running the script also imported missing css definitions.

For other people using react - the files should be copied to `public`.

The behaviour is unconventional usually when installing packages the expectation is that they should be importable via `import ... from '...' `.

is there a reason for not following the pattern?

**Comment by shaielc** [comment]
I think I understand please correct me if I am wrong:
* Thebe uses code from the `@jupyter` packages in a way that makes it hard for some build systems to infer the dependencies.
* A solution with pre-built bundles was chosen as `thebe` should be framework agnostic.

Is it possible use ES6 like imports with pre-built bundles?
Also adding the `copy-thebe-assets.cjs` to the package will be usefull IMO.

I think there's a need to update `thebe-react` README to reflect the process, could be a reference to https://mystmd.org/thebe/react-lite.
but one of them needs to have a "Quickstart" section with the above method of installation.

**Comment by stevejpurves** [comment]
@shaielc I think in order to use ES6 style imports, we'd need to build bundled ESM modules at the least? previously there was heavy reliance on webpack features in the juptyerlab and lite codebases and build systems, for example inline file-loader syntax was used, and this was one of the reasons for bundling lite especially.

However, things have moved on in the jupyterlite code base so it's maybe an idea to revisit and re-asses the need for bundling at some point.

👍🏼 on updating the readme AND on including teh script in the package, just shipping it in a bin folder would suffice do you think?
