### ISSUE TITLE
Notebook execution Idle MyST+thebe website

### ISSUE THREAD

**Issue by cmarmo** [executablebooks/thebe#699]
### Describe the bug

Dear maintainers,

I am experimenting with the integration of thebe directly in a MyST generated website as detailed [here](https://mystmd.org/guide/integrating-jupyter).
I understand this is a beta feature, but it is also an excellent feature... :) , so if I can help in any way I would be happy to...

I have tested the three options of notebook evaluation: jupyterLite, binder and a local jupyterlab.

The three seem to correctly connect to the computing server, but the cells are not executed and the debug logs report
```
idle executeCells executed 2 cells
idle executeAll
``` 
The logs are slightly different for the three solutions but the result is the same (Idle message...).

- With binder the logs contain a certain amount of cross-origin issues: eg
```
Cookie “username-notebooks-gesis-org” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite
```

- with JupyterLite the issue seems to be
```
GET
http://localhost:3000/pypi/all.json
[HTTP/1.1 404 Article was not found 0ms]
```

- for the local jupyterlab I really have no idea as I started it with 
```
jupyter lab --NotebookApp.token=test-secret --NotebookApp.allow_origin='*'
```
to avoid issues with cross-origin...

Thank you for your attention.

### Reproduce the bug

I have created a [repository](https://github.com/cmarmo/test-thebe/) to reproduce the failure.
The `myst.yml` can be modified to cover each connection case.

 

### List your environment

```
myst v1.1.26
node v21.1.0
npm v10.2.0
firefox v 119.0
```
`thebe`version should be tho one districbuted with the [MyST Book theme](https://github.com/myst-templates/book-theme) if I understand correctly.

**Comment by cmarmo** [comment]
I've finally realized where to look for the local jupyter lab logs.
```
tornado.web.HTTPError: HTTP 404: Not Found (file or directory does not exist: 'test-thebe-test-thebe.ipynb')
```
Apparently the name of the notebook is rewritten somewhere and the server looks for 'test-thebe-test-thebe.ipynb' rather than 'test-thebe/test-thebe.ipynb'?
Is it possible?

**Comment by stevejpurves** [comment]
Hi @cmarmo - thanks for reporting this! and I can confirm the issues you are seeing.
The cells are being executed and completing e..g see the console log messages:
```
attached Attached to session
thebe-core.min.js:2 executing executeAll
thebe-core.min.js:2 executing executeCells 2 cells
thebe-core.min.js:2 idle executeCells executed 2 cells
thebe-core.min.js:2 idle executeAll
```
but then the webpage is not actually updating, which I think is a bug in myst theme. I'm actively working on things there so should be able to track this down and get a fix out.

On the naming of notebooks, that naming is actually ok and is related to the stub you see in the url. As the notebooks don't actually exist on the server, the name could be anything and we use the convention f"{location}/{stub}-{notebook}.ipynb` to name them (aside: this is to allow myst-theme to so things like run a notebook in the context of a figure embedded in another markdown file) where only the `location` is critical to correct execution.

(I can only generate that jupyter lab tornado error when clicking on the active session via the jupyter lab interface)

**Comment by cmarmo** [comment]
Thank you @stevejpurves for your clear and detailed answer!
It would be awesome if you can get a fix.
I was planning to use this solution for a pedagogical platform.

**Comment by stevejpurves** [comment]
update: If I create a `test_thebe.ipynb` file, with the exact same cells then it works, something very subtle is happening when using an `md` based notebook. It's a very subtle difference in how myst is parsing the notebook -- issue open here: https://github.com/executablebooks/mystmd/issues/748

**Comment by stevejpurves** [comment]
@cmarmo we've made the upstream fix to mystmd that should fix this issue. if you could reinstall the latest mystmd and try again, it should work. I based my test case on your original buggy repo

**Comment by cmarmo** [comment]
Hi @stevejpurves , I can confirm that the execution of the notebooks is working now .... even in some more complex examples I'm working on.
Thank you very much for your work!
Happy new year to you and your colleagues from executablebooks!

**Comment by stevejpurves** [comment]
that's great @cmarmo - please let us know where you run into more problems / limitations as you go!
