### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by Vislesha** [executablebooks/thebe#719]
### Context

This is a very interesting library and would help a lot in our application to provide some interactive executable scenarios for data explorations! However, we are using Angular as our front end framework and could not find any specific resource how to integrate into an Angular app.  Wondering if there are any plans to support/provide an angular version like 'thebe-react'?

**Comment by stevejpurves** [comment]
Hi @Vislesha thanks for the question!
There are no plans to make an angular wrapper, we've seen a lot of react activity around the jupyter ecosystem in terms of front ends and widgets but not much angular. So on one hand we've not considered it but also it's outside of the stack we're used to working with. If someone wanted to build that out we'd be happy to interact and maybe some aspects of thebe-react could help guide things there?

Just for some context, what does your angular app do? (I'm curious about what kind of interaction/UX you'd be trying to use thebe to provider)

**Comment by stevejpurves** [comment]
@Vislesha sounds like a good use case for sure. If you go down the integration route feel free to email/ping me directly, or reopen this issue if you have questions -- closing for now
