### ISSUE TITLE
Timeline for production version

### ISSUE THREAD

**Issue by Vislesha** [executablebooks/thebe#746]
Hi Team: Any timeline for a production version of this library? 
Thanks!

**Comment by stevejpurves** [comment]
Hi @Vislesha this library is currently in use in [executablebooks/myst-theme](https://github.com/executablebooks/myst-theme) in a "production" setting and usage in that library is driving the development direction, but a the same time serving a few different use cases from drop-on-page usage for simple html, to react integration and exposing jupyerlite/pyodide as a backend. 

Can you give some more details on how you'd be using the library, or what you'd like to see before you started using it? i.e. which aspects/features you are interested in.

**Comment by stevejpurves** [comment]
Hi @Vislesha - yes, it can help with those features but to achieve it I would focus on `thebe-core` and using that part of the library for connection & session management. 

That part of the library tries to be pretty framework agnostic, and mainly just wraps the JupyterLab services for you and provides some abstractions around notebooks and cells. `thebe-lite` is a drop in alongside `thebe-core` to take a closer look at that run the core demo `npm run demo:core` that is in https://github.com/executablebooks/thebe/tree/main/apps/demo-core
